sudo: required
service:
    - docker

before_install: 
    - docker build -t nahid08/docker-react -f Dockerfile.dev .

script:
    - docker run nahid08/docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-443118411418"
    bucket_path: "docker"
    on: 
     branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY